// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	auth "developer-portal-backend/internal/auth"
	models "developer-portal-backend/internal/database/models"
	service "developer-portal-backend/internal/service"
	json "encoding/json"
	multipart "mime/multipart"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// AddQuickLink mocks base method.
func (m *MockUserServiceInterface) AddQuickLink(id uuid.UUID, req *service.AddQuickLinkRequest) (*service.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddQuickLink", id, req)
	ret0, _ := ret[0].(*service.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddQuickLink indicates an expected call of AddQuickLink.
func (mr *MockUserServiceInterfaceMockRecorder) AddQuickLink(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddQuickLink", reflect.TypeOf((*MockUserServiceInterface)(nil).AddQuickLink), id, req)
}

// CreateUser mocks base method.
func (m *MockUserServiceInterface) CreateUser(req *service.CreateUserRequest) (*service.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", req)
	ret0, _ := ret[0].(*service.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceInterfaceMockRecorder) CreateUser(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceInterface)(nil).CreateUser), req)
}

// DeleteUser mocks base method.
func (m *MockUserServiceInterface) DeleteUser(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceInterfaceMockRecorder) DeleteUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServiceInterface)(nil).DeleteUser), id)
}

// GetActiveUsers mocks base method.
func (m *MockUserServiceInterface) GetActiveUsers(organizationID uuid.UUID, limit, offset int) ([]service.UserResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsers", organizationID, limit, offset)
	ret0, _ := ret[0].([]service.UserResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActiveUsers indicates an expected call of GetActiveUsers.
func (mr *MockUserServiceInterfaceMockRecorder) GetActiveUsers(organizationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsers", reflect.TypeOf((*MockUserServiceInterface)(nil).GetActiveUsers), organizationID, limit, offset)
}

// GetQuickLinks mocks base method.
func (m *MockUserServiceInterface) GetQuickLinks(id uuid.UUID) (*service.QuickLinksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuickLinks", id)
	ret0, _ := ret[0].(*service.QuickLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuickLinks indicates an expected call of GetQuickLinks.
func (mr *MockUserServiceInterfaceMockRecorder) GetQuickLinks(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuickLinks", reflect.TypeOf((*MockUserServiceInterface)(nil).GetQuickLinks), id)
}

// GetUserByID mocks base method.
func (m *MockUserServiceInterface) GetUserByID(id uuid.UUID) (*service.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(*service.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceInterfaceMockRecorder) GetUserByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUserByID), id)
}

// GetUsersByOrganization mocks base method.
func (m *MockUserServiceInterface) GetUsersByOrganization(organizationID uuid.UUID, limit, offset int) ([]service.UserResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByOrganization", organizationID, limit, offset)
	ret0, _ := ret[0].([]service.UserResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUsersByOrganization indicates an expected call of GetUsersByOrganization.
func (mr *MockUserServiceInterfaceMockRecorder) GetUsersByOrganization(organizationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByOrganization", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUsersByOrganization), organizationID, limit, offset)
}

// RemoveQuickLink mocks base method.
func (m *MockUserServiceInterface) RemoveQuickLink(id uuid.UUID, linkURL string) (*service.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveQuickLink", id, linkURL)
	ret0, _ := ret[0].(*service.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveQuickLink indicates an expected call of RemoveQuickLink.
func (mr *MockUserServiceInterfaceMockRecorder) RemoveQuickLink(id, linkURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveQuickLink", reflect.TypeOf((*MockUserServiceInterface)(nil).RemoveQuickLink), id, linkURL)
}

// SearchUsers mocks base method.
func (m *MockUserServiceInterface) SearchUsers(organizationID uuid.UUID, query string, limit, offset int) ([]service.UserResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", organizationID, query, limit, offset)
	ret0, _ := ret[0].([]service.UserResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockUserServiceInterfaceMockRecorder) SearchUsers(organizationID, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockUserServiceInterface)(nil).SearchUsers), organizationID, query, limit, offset)
}

// UpdateUser mocks base method.
func (m *MockUserServiceInterface) UpdateUser(id uuid.UUID, req *service.UpdateUserRequest) (*service.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", id, req)
	ret0, _ := ret[0].(*service.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateUser(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateUser), id, req)
}


// MockTeamServiceInterface is a mock of TeamServiceInterface interface.
type MockTeamServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTeamServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTeamServiceInterfaceMockRecorder is the mock recorder for MockTeamServiceInterface.
type MockTeamServiceInterfaceMockRecorder struct {
	mock *MockTeamServiceInterface
}

// NewMockTeamServiceInterface creates a new mock instance.
func NewMockTeamServiceInterface(ctrl *gomock.Controller) *MockTeamServiceInterface {
	mock := &MockTeamServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTeamServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamServiceInterface) EXPECT() *MockTeamServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamServiceInterface) Create(req *service.CreateTeamRequest) (*service.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*service.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamServiceInterfaceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamServiceInterface)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockTeamServiceInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamServiceInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamServiceInterface)(nil).Delete), id)
}

// GetAllTeams mocks base method.
func (m *MockTeamServiceInterface) GetAllTeams(organizationID *uuid.UUID, page, pageSize int) (*service.TeamListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTeams", organizationID, page, pageSize)
	ret0, _ := ret[0].(*service.TeamListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTeams indicates an expected call of GetAllTeams.
func (mr *MockTeamServiceInterfaceMockRecorder) GetAllTeams(organizationID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTeams", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetAllTeams), organizationID, page, pageSize)
}

// GetByID mocks base method.
func (m *MockTeamServiceInterface) GetByID(id uuid.UUID) (*service.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*service.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamServiceInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockTeamServiceInterface) GetByName(groupID uuid.UUID, name string) (*service.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", groupID, name)
	ret0, _ := ret[0].(*service.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamServiceInterfaceMockRecorder) GetByName(groupID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetByName), groupID, name)
}

// GetByOrganization mocks base method.
func (m *MockTeamServiceInterface) GetByOrganization(organizationID uuid.UUID, page, pageSize int) (*service.TeamListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganization", organizationID, page, pageSize)
	ret0, _ := ret[0].(*service.TeamListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrganization indicates an expected call of GetByOrganization.
func (mr *MockTeamServiceInterfaceMockRecorder) GetByOrganization(organizationID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganization", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetByOrganization), organizationID, page, pageSize)
}

// GetBySimpleName mocks base method.
func (m *MockTeamServiceInterface) GetBySimpleName(teamName string) (*service.TeamWithMembersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySimpleName", teamName)
	ret0, _ := ret[0].(*service.TeamWithMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySimpleName indicates an expected call of GetBySimpleName.
func (mr *MockTeamServiceInterfaceMockRecorder) GetBySimpleName(teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySimpleName", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetBySimpleName), teamName)
}

// GetBySimpleNameWithViewer mocks base method.
func (m *MockTeamServiceInterface) GetBySimpleNameWithViewer(teamName, viewerName string) (*service.TeamWithMembersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySimpleNameWithViewer", teamName, viewerName)
	ret0, _ := ret[0].(*service.TeamWithMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySimpleNameWithViewer indicates an expected call of GetBySimpleNameWithViewer.
func (mr *MockTeamServiceInterfaceMockRecorder) GetBySimpleNameWithViewer(teamName, viewerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySimpleNameWithViewer", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetBySimpleNameWithViewer), teamName, viewerName)
}

// GetMembersOnly mocks base method.
func (m *MockTeamServiceInterface) GetMembersOnly(id uuid.UUID) ([]service.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembersOnly", id)
	ret0, _ := ret[0].([]service.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersOnly indicates an expected call of GetMembersOnly.
func (mr *MockTeamServiceInterfaceMockRecorder) GetMembersOnly(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersOnly", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetMembersOnly), id)
}

// GetTeamComponentsByID mocks base method.
func (m *MockTeamServiceInterface) GetTeamComponentsByID(id uuid.UUID, page, pageSize int) ([]models.Component, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamComponentsByID", id, page, pageSize)
	ret0, _ := ret[0].([]models.Component)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTeamComponentsByID indicates an expected call of GetTeamComponentsByID.
func (mr *MockTeamServiceInterfaceMockRecorder) GetTeamComponentsByID(id, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamComponentsByID", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetTeamComponentsByID), id, page, pageSize)
}

// GetTeamComponentsByName mocks base method.
func (m *MockTeamServiceInterface) GetTeamComponentsByName(organizationID uuid.UUID, teamName string, page, pageSize int) ([]models.Component, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamComponentsByName", organizationID, teamName, page, pageSize)
	ret0, _ := ret[0].([]models.Component)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTeamComponentsByName indicates an expected call of GetTeamComponentsByName.
func (mr *MockTeamServiceInterfaceMockRecorder) GetTeamComponentsByName(organizationID, teamName, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamComponentsByName", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetTeamComponentsByName), organizationID, teamName, page, pageSize)
}

// GetTeamMembersByName mocks base method.
func (m *MockTeamServiceInterface) GetTeamMembersByName(organizationID uuid.UUID, teamName string, page, pageSize int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamMembersByName", organizationID, teamName, page, pageSize)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTeamMembersByName indicates an expected call of GetTeamMembersByName.
func (mr *MockTeamServiceInterfaceMockRecorder) GetTeamMembersByName(organizationID, teamName, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamMembersByName", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetTeamMembersByName), organizationID, teamName, page, pageSize)
}

// GetWithComponentOwnerships mocks base method.
func (m *MockTeamServiceInterface) GetWithComponentOwnerships(id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithComponentOwnerships", id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithComponentOwnerships indicates an expected call of GetWithComponentOwnerships.
func (mr *MockTeamServiceInterfaceMockRecorder) GetWithComponentOwnerships(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithComponentOwnerships", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetWithComponentOwnerships), id)
}

// GetWithDutySchedules mocks base method.
func (m *MockTeamServiceInterface) GetWithDutySchedules(id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDutySchedules", id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDutySchedules indicates an expected call of GetWithDutySchedules.
func (mr *MockTeamServiceInterfaceMockRecorder) GetWithDutySchedules(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDutySchedules", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetWithDutySchedules), id)
}

// GetWithMembers mocks base method.
func (m *MockTeamServiceInterface) GetWithMembers(id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithMembers", id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithMembers indicates an expected call of GetWithMembers.
func (mr *MockTeamServiceInterfaceMockRecorder) GetWithMembers(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithMembers", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetWithMembers), id)
}

// GetWithProjects mocks base method.
func (m *MockTeamServiceInterface) GetWithProjects(id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithProjects", id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithProjects indicates an expected call of GetWithProjects.
func (mr *MockTeamServiceInterfaceMockRecorder) GetWithProjects(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithProjects", reflect.TypeOf((*MockTeamServiceInterface)(nil).GetWithProjects), id)
}

// Search mocks base method.
func (m *MockTeamServiceInterface) Search(organizationID uuid.UUID, query string, page, pageSize int) (*service.TeamListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", organizationID, query, page, pageSize)
	ret0, _ := ret[0].(*service.TeamListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockTeamServiceInterfaceMockRecorder) Search(organizationID, query, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockTeamServiceInterface)(nil).Search), organizationID, query, page, pageSize)
}

// Update mocks base method.
func (m *MockTeamServiceInterface) Update(id uuid.UUID, req *service.UpdateTeamRequest) (*service.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*service.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamServiceInterfaceMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamServiceInterface)(nil).Update), id, req)
}

// UpdateTeamMetadata mocks base method.
func (m *MockTeamServiceInterface) UpdateTeamMetadata(id uuid.UUID, metadata json.RawMessage) (*service.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamMetadata", id, metadata)
	ret0, _ := ret[0].(*service.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeamMetadata indicates an expected call of UpdateTeamMetadata.
func (mr *MockTeamServiceInterfaceMockRecorder) UpdateTeamMetadata(id, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamMetadata", reflect.TypeOf((*MockTeamServiceInterface)(nil).UpdateTeamMetadata), id, metadata)
}

// MockProjectServiceInterface is a mock of ProjectServiceInterface interface.
type MockProjectServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockProjectServiceInterfaceMockRecorder is the mock recorder for MockProjectServiceInterface.
type MockProjectServiceInterfaceMockRecorder struct {
	mock *MockProjectServiceInterface
}

// NewMockProjectServiceInterface creates a new mock instance.
func NewMockProjectServiceInterface(ctrl *gomock.Controller) *MockProjectServiceInterface {
	mock := &MockProjectServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProjectServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectServiceInterface) EXPECT() *MockProjectServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteProject mocks base method.
func (m *MockProjectServiceInterface) DeleteProject(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectServiceInterfaceMockRecorder) DeleteProject(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectServiceInterface)(nil).DeleteProject), id)
}

// MockComponentServiceInterface is a mock of ComponentServiceInterface interface.
type MockComponentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockComponentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockComponentServiceInterfaceMockRecorder is the mock recorder for MockComponentServiceInterface.
type MockComponentServiceInterfaceMockRecorder struct {
	mock *MockComponentServiceInterface
}

// NewMockComponentServiceInterface creates a new mock instance.
func NewMockComponentServiceInterface(ctrl *gomock.Controller) *MockComponentServiceInterface {
	mock := &MockComponentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockComponentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentServiceInterface) EXPECT() *MockComponentServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteComponent mocks base method.
func (m *MockComponentServiceInterface) DeleteComponent(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComponent", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComponent indicates an expected call of DeleteComponent.
func (mr *MockComponentServiceInterfaceMockRecorder) DeleteComponent(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComponent", reflect.TypeOf((*MockComponentServiceInterface)(nil).DeleteComponent), id)
}

// MockLandscapeServiceInterface is a mock of LandscapeServiceInterface interface.
type MockLandscapeServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLandscapeServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockLandscapeServiceInterfaceMockRecorder is the mock recorder for MockLandscapeServiceInterface.
type MockLandscapeServiceInterfaceMockRecorder struct {
	mock *MockLandscapeServiceInterface
}

// NewMockLandscapeServiceInterface creates a new mock instance.
func NewMockLandscapeServiceInterface(ctrl *gomock.Controller) *MockLandscapeServiceInterface {
	mock := &MockLandscapeServiceInterface{ctrl: ctrl}
	mock.recorder = &MockLandscapeServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLandscapeServiceInterface) EXPECT() *MockLandscapeServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateLandscape mocks base method.
func (m *MockLandscapeServiceInterface) CreateLandscape(req *service.CreateLandscapeRequest) (*service.LandscapeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLandscape", req)
	ret0, _ := ret[0].(*service.LandscapeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLandscape indicates an expected call of CreateLandscape.
func (mr *MockLandscapeServiceInterfaceMockRecorder) CreateLandscape(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLandscape", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).CreateLandscape), req)
}

// DeleteLandscape mocks base method.
func (m *MockLandscapeServiceInterface) DeleteLandscape(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLandscape", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLandscape indicates an expected call of DeleteLandscape.
func (mr *MockLandscapeServiceInterfaceMockRecorder) DeleteLandscape(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLandscape", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).DeleteLandscape), id)
}

// GetByProjectName mocks base method.
func (m *MockLandscapeServiceInterface) GetByProjectName(projectName string) (*service.LandscapeListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectName", projectName)
	ret0, _ := ret[0].(*service.LandscapeListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectName indicates an expected call of GetByProjectName.
func (mr *MockLandscapeServiceInterfaceMockRecorder) GetByProjectName(projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectName", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).GetByProjectName), projectName)
}

// GetByProjectNameAll mocks base method.
func (m *MockLandscapeServiceInterface) GetByProjectNameAll(projectName string) ([]service.LandscapeMinimalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectNameAll", projectName)
	ret0, _ := ret[0].([]service.LandscapeMinimalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectNameAll indicates an expected call of GetByProjectNameAll.
func (mr *MockLandscapeServiceInterfaceMockRecorder) GetByProjectNameAll(projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectNameAll", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).GetByProjectNameAll), projectName)
}

// GetLandscapeByID mocks base method.
func (m *MockLandscapeServiceInterface) GetLandscapeByID(id uuid.UUID) (*service.LandscapeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLandscapeByID", id)
	ret0, _ := ret[0].(*service.LandscapeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLandscapeByID indicates an expected call of GetLandscapeByID.
func (mr *MockLandscapeServiceInterfaceMockRecorder) GetLandscapeByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLandscapeByID", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).GetLandscapeByID), id)
}

// GetLandscapesByOrganization mocks base method.
func (m *MockLandscapeServiceInterface) GetLandscapesByOrganization(organizationID uuid.UUID, limit, offset int) ([]service.LandscapeResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLandscapesByOrganization", organizationID, limit, offset)
	ret0, _ := ret[0].([]service.LandscapeResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLandscapesByOrganization indicates an expected call of GetLandscapesByOrganization.
func (mr *MockLandscapeServiceInterfaceMockRecorder) GetLandscapesByOrganization(organizationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLandscapesByOrganization", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).GetLandscapesByOrganization), organizationID, limit, offset)
}

// ListByQuery mocks base method.
func (m *MockLandscapeServiceInterface) ListByQuery(q string, domains, environments []string, limit, offset int) (*service.LandscapeListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByQuery", q, domains, environments, limit, offset)
	ret0, _ := ret[0].(*service.LandscapeListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByQuery indicates an expected call of ListByQuery.
func (mr *MockLandscapeServiceInterfaceMockRecorder) ListByQuery(q, domains, environments, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByQuery", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).ListByQuery), q, domains, environments, limit, offset)
}

// UpdateLandscape mocks base method.
func (m *MockLandscapeServiceInterface) UpdateLandscape(id uuid.UUID, req *service.UpdateLandscapeRequest) (*service.LandscapeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLandscape", id, req)
	ret0, _ := ret[0].(*service.LandscapeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLandscape indicates an expected call of UpdateLandscape.
func (mr *MockLandscapeServiceInterfaceMockRecorder) UpdateLandscape(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLandscape", reflect.TypeOf((*MockLandscapeServiceInterface)(nil).UpdateLandscape), id, req)
}


// MockGitHubServiceInterface is a mock of GitHubServiceInterface interface.
type MockGitHubServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockGitHubServiceInterfaceMockRecorder is the mock recorder for MockGitHubServiceInterface.
type MockGitHubServiceInterfaceMockRecorder struct {
	mock *MockGitHubServiceInterface
}

// NewMockGitHubServiceInterface creates a new mock instance.
func NewMockGitHubServiceInterface(ctrl *gomock.Controller) *MockGitHubServiceInterface {
	mock := &MockGitHubServiceInterface{ctrl: ctrl}
	mock.recorder = &MockGitHubServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubServiceInterface) EXPECT() *MockGitHubServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAveragePRMergeTime mocks base method.
func (m *MockGitHubServiceInterface) GetAveragePRMergeTime(ctx context.Context, claims *auth.AuthClaims, period string) (*service.AveragePRMergeTimeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAveragePRMergeTime", ctx, claims, period)
	ret0, _ := ret[0].(*service.AveragePRMergeTimeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAveragePRMergeTime indicates an expected call of GetAveragePRMergeTime.
func (mr *MockGitHubServiceInterfaceMockRecorder) GetAveragePRMergeTime(ctx, claims, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAveragePRMergeTime", reflect.TypeOf((*MockGitHubServiceInterface)(nil).GetAveragePRMergeTime), ctx, claims, period)
}

// GetContributionsHeatmap mocks base method.
func (m *MockGitHubServiceInterface) GetContributionsHeatmap(ctx context.Context, claims *auth.AuthClaims, period string) (*service.ContributionsHeatmapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContributionsHeatmap", ctx, claims, period)
	ret0, _ := ret[0].(*service.ContributionsHeatmapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContributionsHeatmap indicates an expected call of GetContributionsHeatmap.
func (mr *MockGitHubServiceInterfaceMockRecorder) GetContributionsHeatmap(ctx, claims, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContributionsHeatmap", reflect.TypeOf((*MockGitHubServiceInterface)(nil).GetContributionsHeatmap), ctx, claims, period)
}

// GetGitHubAsset mocks base method.
func (m *MockGitHubServiceInterface) GetGitHubAsset(ctx context.Context, claims *auth.AuthClaims, assetURL string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitHubAsset", ctx, claims, assetURL)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGitHubAsset indicates an expected call of GetGitHubAsset.
func (mr *MockGitHubServiceInterfaceMockRecorder) GetGitHubAsset(ctx, claims, assetURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitHubAsset", reflect.TypeOf((*MockGitHubServiceInterface)(nil).GetGitHubAsset), ctx, claims, assetURL)
}

// GetRepositoryContent mocks base method.
func (m *MockGitHubServiceInterface) GetRepositoryContent(ctx context.Context, claims *auth.AuthClaims, owner, repo, path, ref string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryContent", ctx, claims, owner, repo, path, ref)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryContent indicates an expected call of GetRepositoryContent.
func (mr *MockGitHubServiceInterfaceMockRecorder) GetRepositoryContent(ctx, claims, owner, repo, path, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryContent", reflect.TypeOf((*MockGitHubServiceInterface)(nil).GetRepositoryContent), ctx, claims, owner, repo, path, ref)
}

// GetUserOpenPullRequests mocks base method.
func (m *MockGitHubServiceInterface) GetUserOpenPullRequests(ctx context.Context, claims *auth.AuthClaims, state, sort, direction string, perPage, page int) (*service.PullRequestsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOpenPullRequests", ctx, claims, state, sort, direction, perPage, page)
	ret0, _ := ret[0].(*service.PullRequestsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOpenPullRequests indicates an expected call of GetUserOpenPullRequests.
func (mr *MockGitHubServiceInterfaceMockRecorder) GetUserOpenPullRequests(ctx, claims, state, sort, direction, perPage, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOpenPullRequests", reflect.TypeOf((*MockGitHubServiceInterface)(nil).GetUserOpenPullRequests), ctx, claims, state, sort, direction, perPage, page)
}

// GetUserTotalContributions mocks base method.
func (m *MockGitHubServiceInterface) GetUserTotalContributions(ctx context.Context, claims *auth.AuthClaims, period string) (*service.TotalContributionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTotalContributions", ctx, claims, period)
	ret0, _ := ret[0].(*service.TotalContributionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTotalContributions indicates an expected call of GetUserTotalContributions.
func (mr *MockGitHubServiceInterfaceMockRecorder) GetUserTotalContributions(ctx, claims, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTotalContributions", reflect.TypeOf((*MockGitHubServiceInterface)(nil).GetUserTotalContributions), ctx, claims, period)
}

// UpdateRepositoryFile mocks base method.
func (m *MockGitHubServiceInterface) UpdateRepositoryFile(ctx context.Context, claims *auth.AuthClaims, owner, repo, path, message, content, sha, branch string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepositoryFile", ctx, claims, owner, repo, path, message, content, sha, branch)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRepositoryFile indicates an expected call of UpdateRepositoryFile.
func (mr *MockGitHubServiceInterfaceMockRecorder) UpdateRepositoryFile(ctx, claims, owner, repo, path, message, content, sha, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepositoryFile", reflect.TypeOf((*MockGitHubServiceInterface)(nil).UpdateRepositoryFile), ctx, claims, owner, repo, path, message, content, sha, branch)
}

// MockJenkinsServiceInterface is a mock of JenkinsServiceInterface interface.
type MockJenkinsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJenkinsServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockJenkinsServiceInterfaceMockRecorder is the mock recorder for MockJenkinsServiceInterface.
type MockJenkinsServiceInterfaceMockRecorder struct {
	mock *MockJenkinsServiceInterface
}

// NewMockJenkinsServiceInterface creates a new mock instance.
func NewMockJenkinsServiceInterface(ctrl *gomock.Controller) *MockJenkinsServiceInterface {
	mock := &MockJenkinsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockJenkinsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJenkinsServiceInterface) EXPECT() *MockJenkinsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetBuildStatus mocks base method.
func (m *MockJenkinsServiceInterface) GetBuildStatus(ctx context.Context, jaasName, jobName string, buildNumber int) (*service.JenkinsBuildStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildStatus", ctx, jaasName, jobName, buildNumber)
	ret0, _ := ret[0].(*service.JenkinsBuildStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildStatus indicates an expected call of GetBuildStatus.
func (mr *MockJenkinsServiceInterfaceMockRecorder) GetBuildStatus(ctx, jaasName, jobName, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildStatus", reflect.TypeOf((*MockJenkinsServiceInterface)(nil).GetBuildStatus), ctx, jaasName, jobName, buildNumber)
}

// GetJobParameters mocks base method.
func (m *MockJenkinsServiceInterface) GetJobParameters(ctx context.Context, jaasName, jobName string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobParameters", ctx, jaasName, jobName)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobParameters indicates an expected call of GetJobParameters.
func (mr *MockJenkinsServiceInterfaceMockRecorder) GetJobParameters(ctx, jaasName, jobName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobParameters", reflect.TypeOf((*MockJenkinsServiceInterface)(nil).GetJobParameters), ctx, jaasName, jobName)
}

// GetQueueItemStatus mocks base method.
func (m *MockJenkinsServiceInterface) GetQueueItemStatus(ctx context.Context, jaasName, queueItemID string) (*service.JenkinsQueueStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueItemStatus", ctx, jaasName, queueItemID)
	ret0, _ := ret[0].(*service.JenkinsQueueStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueItemStatus indicates an expected call of GetQueueItemStatus.
func (mr *MockJenkinsServiceInterfaceMockRecorder) GetQueueItemStatus(ctx, jaasName, queueItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueItemStatus", reflect.TypeOf((*MockJenkinsServiceInterface)(nil).GetQueueItemStatus), ctx, jaasName, queueItemID)
}

// TriggerJob mocks base method.
func (m *MockJenkinsServiceInterface) TriggerJob(ctx context.Context, jaasName, jobName string, parameters map[string]string) (*service.JenkinsTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerJob", ctx, jaasName, jobName, parameters)
	ret0, _ := ret[0].(*service.JenkinsTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerJob indicates an expected call of TriggerJob.
func (mr *MockJenkinsServiceInterfaceMockRecorder) TriggerJob(ctx, jaasName, jobName, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerJob", reflect.TypeOf((*MockJenkinsServiceInterface)(nil).TriggerJob), ctx, jaasName, jobName, parameters)
}

// MockSonarServiceInterface is a mock of SonarServiceInterface interface.
type MockSonarServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSonarServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockSonarServiceInterfaceMockRecorder is the mock recorder for MockSonarServiceInterface.
type MockSonarServiceInterfaceMockRecorder struct {
	mock *MockSonarServiceInterface
}

// NewMockSonarServiceInterface creates a new mock instance.
func NewMockSonarServiceInterface(ctrl *gomock.Controller) *MockSonarServiceInterface {
	mock := &MockSonarServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSonarServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSonarServiceInterface) EXPECT() *MockSonarServiceInterfaceMockRecorder {
	return m.recorder
}

// GetComponentMeasures mocks base method.
func (m *MockSonarServiceInterface) GetComponentMeasures(projectKey string) (*service.SonarCombinedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentMeasures", projectKey)
	ret0, _ := ret[0].(*service.SonarCombinedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponentMeasures indicates an expected call of GetComponentMeasures.
func (mr *MockSonarServiceInterfaceMockRecorder) GetComponentMeasures(projectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentMeasures", reflect.TypeOf((*MockSonarServiceInterface)(nil).GetComponentMeasures), projectKey)
}

// MockJiraServiceInterface is a mock of JiraServiceInterface interface.
type MockJiraServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJiraServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockJiraServiceInterfaceMockRecorder is the mock recorder for MockJiraServiceInterface.
type MockJiraServiceInterfaceMockRecorder struct {
	mock *MockJiraServiceInterface
}

// NewMockJiraServiceInterface creates a new mock instance.
func NewMockJiraServiceInterface(ctrl *gomock.Controller) *MockJiraServiceInterface {
	mock := &MockJiraServiceInterface{ctrl: ctrl}
	mock.recorder = &MockJiraServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJiraServiceInterface) EXPECT() *MockJiraServiceInterfaceMockRecorder {
	return m.recorder
}

// GetIssues mocks base method.
func (m *MockJiraServiceInterface) GetIssues(filters service.JiraIssueFilters) (*service.JiraIssuesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssues", filters)
	ret0, _ := ret[0].(*service.JiraIssuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssues indicates an expected call of GetIssues.
func (mr *MockJiraServiceInterfaceMockRecorder) GetIssues(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssues", reflect.TypeOf((*MockJiraServiceInterface)(nil).GetIssues), filters)
}

// GetIssuesCount mocks base method.
func (m *MockJiraServiceInterface) GetIssuesCount(filters service.JiraIssueFilters) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssuesCount", filters)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuesCount indicates an expected call of GetIssuesCount.
func (mr *MockJiraServiceInterfaceMockRecorder) GetIssuesCount(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuesCount", reflect.TypeOf((*MockJiraServiceInterface)(nil).GetIssuesCount), filters)
}

// MockAICoreServiceInterface is a mock of AICoreServiceInterface interface.
type MockAICoreServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAICoreServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAICoreServiceInterfaceMockRecorder is the mock recorder for MockAICoreServiceInterface.
type MockAICoreServiceInterfaceMockRecorder struct {
	mock *MockAICoreServiceInterface
}

// NewMockAICoreServiceInterface creates a new mock instance.
func NewMockAICoreServiceInterface(ctrl *gomock.Controller) *MockAICoreServiceInterface {
	mock := &MockAICoreServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAICoreServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAICoreServiceInterface) EXPECT() *MockAICoreServiceInterfaceMockRecorder {
	return m.recorder
}

// ChatInference mocks base method.
func (m *MockAICoreServiceInterface) ChatInference(c *gin.Context, req *service.AICoreInferenceRequest) (*service.AICoreInferenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatInference", c, req)
	ret0, _ := ret[0].(*service.AICoreInferenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatInference indicates an expected call of ChatInference.
func (mr *MockAICoreServiceInterfaceMockRecorder) ChatInference(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatInference", reflect.TypeOf((*MockAICoreServiceInterface)(nil).ChatInference), c, req)
}

// CreateConfiguration mocks base method.
func (m *MockAICoreServiceInterface) CreateConfiguration(c *gin.Context, req *service.AICoreConfigurationRequest) (*service.AICoreConfigurationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfiguration", c, req)
	ret0, _ := ret[0].(*service.AICoreConfigurationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfiguration indicates an expected call of CreateConfiguration.
func (mr *MockAICoreServiceInterfaceMockRecorder) CreateConfiguration(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfiguration", reflect.TypeOf((*MockAICoreServiceInterface)(nil).CreateConfiguration), c, req)
}

// CreateDeployment mocks base method.
func (m *MockAICoreServiceInterface) CreateDeployment(c *gin.Context, req *service.AICoreDeploymentRequest) (*service.AICoreDeploymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeployment", c, req)
	ret0, _ := ret[0].(*service.AICoreDeploymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeployment indicates an expected call of CreateDeployment.
func (mr *MockAICoreServiceInterfaceMockRecorder) CreateDeployment(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeployment", reflect.TypeOf((*MockAICoreServiceInterface)(nil).CreateDeployment), c, req)
}

// DeleteDeployment mocks base method.
func (m *MockAICoreServiceInterface) DeleteDeployment(c *gin.Context, deploymentID string) (*service.AICoreDeploymentDeletionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeployment", c, deploymentID)
	ret0, _ := ret[0].(*service.AICoreDeploymentDeletionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDeployment indicates an expected call of DeleteDeployment.
func (mr *MockAICoreServiceInterfaceMockRecorder) DeleteDeployment(c, deploymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeployment", reflect.TypeOf((*MockAICoreServiceInterface)(nil).DeleteDeployment), c, deploymentID)
}

// GetConfigurations mocks base method.
func (m *MockAICoreServiceInterface) GetConfigurations(c *gin.Context) (*service.AICoreConfigurationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigurations", c)
	ret0, _ := ret[0].(*service.AICoreConfigurationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigurations indicates an expected call of GetConfigurations.
func (mr *MockAICoreServiceInterfaceMockRecorder) GetConfigurations(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurations", reflect.TypeOf((*MockAICoreServiceInterface)(nil).GetConfigurations), c)
}

// GetDeploymentDetails mocks base method.
func (m *MockAICoreServiceInterface) GetDeploymentDetails(c *gin.Context, deploymentID string) (*service.AICoreDeploymentDetailsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentDetails", c, deploymentID)
	ret0, _ := ret[0].(*service.AICoreDeploymentDetailsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentDetails indicates an expected call of GetDeploymentDetails.
func (mr *MockAICoreServiceInterfaceMockRecorder) GetDeploymentDetails(c, deploymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentDetails", reflect.TypeOf((*MockAICoreServiceInterface)(nil).GetDeploymentDetails), c, deploymentID)
}

// GetDeployments mocks base method.
func (m *MockAICoreServiceInterface) GetDeployments(c *gin.Context) (*service.AICoreDeploymentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployments", c)
	ret0, _ := ret[0].(*service.AICoreDeploymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployments indicates an expected call of GetDeployments.
func (mr *MockAICoreServiceInterfaceMockRecorder) GetDeployments(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployments", reflect.TypeOf((*MockAICoreServiceInterface)(nil).GetDeployments), c)
}

// GetMe mocks base method.
func (m *MockAICoreServiceInterface) GetMe(c *gin.Context) (*service.AICoreMeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", c)
	ret0, _ := ret[0].(*service.AICoreMeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockAICoreServiceInterfaceMockRecorder) GetMe(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockAICoreServiceInterface)(nil).GetMe), c)
}

// GetModels mocks base method.
func (m *MockAICoreServiceInterface) GetModels(c *gin.Context, scenarioID string) (*service.AICoreModelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModels", c, scenarioID)
	ret0, _ := ret[0].(*service.AICoreModelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModels indicates an expected call of GetModels.
func (mr *MockAICoreServiceInterfaceMockRecorder) GetModels(c, scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModels", reflect.TypeOf((*MockAICoreServiceInterface)(nil).GetModels), c, scenarioID)
}

// UpdateDeployment mocks base method.
func (m *MockAICoreServiceInterface) UpdateDeployment(c *gin.Context, deploymentID string, req *service.AICoreDeploymentModificationRequest) (*service.AICoreDeploymentModificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeployment", c, deploymentID, req)
	ret0, _ := ret[0].(*service.AICoreDeploymentModificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeployment indicates an expected call of UpdateDeployment.
func (mr *MockAICoreServiceInterfaceMockRecorder) UpdateDeployment(c, deploymentID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeployment", reflect.TypeOf((*MockAICoreServiceInterface)(nil).UpdateDeployment), c, deploymentID, req)
}

// UploadAttachment mocks base method.
func (m *MockAICoreServiceInterface) UploadAttachment(c *gin.Context, file multipart.File, header *multipart.FileHeader) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAttachment", c, file, header)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAttachment indicates an expected call of UploadAttachment.
func (mr *MockAICoreServiceInterfaceMockRecorder) UploadAttachment(c, file, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAttachment", reflect.TypeOf((*MockAICoreServiceInterface)(nil).UploadAttachment), c, file, header)
}

// MockCategoryServiceInterface is a mock of CategoryServiceInterface interface.
type MockCategoryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCategoryServiceInterfaceMockRecorder is the mock recorder for MockCategoryServiceInterface.
type MockCategoryServiceInterfaceMockRecorder struct {
	mock *MockCategoryServiceInterface
}

// NewMockCategoryServiceInterface creates a new mock instance.
func NewMockCategoryServiceInterface(ctrl *gomock.Controller) *MockCategoryServiceInterface {
	mock := &MockCategoryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCategoryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryServiceInterface) EXPECT() *MockCategoryServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockCategoryServiceInterface) GetAll(page, pageSize int) (*service.CategoryListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", page, pageSize)
	ret0, _ := ret[0].(*service.CategoryListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCategoryServiceInterfaceMockRecorder) GetAll(page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCategoryServiceInterface)(nil).GetAll), page, pageSize)
}

// MockLinkServiceInterface is a mock of LinkServiceInterface interface.
type MockLinkServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockLinkServiceInterfaceMockRecorder is the mock recorder for MockLinkServiceInterface.
type MockLinkServiceInterfaceMockRecorder struct {
	mock *MockLinkServiceInterface
}

// NewMockLinkServiceInterface creates a new mock instance.
func NewMockLinkServiceInterface(ctrl *gomock.Controller) *MockLinkServiceInterface {
	mock := &MockLinkServiceInterface{ctrl: ctrl}
	mock.recorder = &MockLinkServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkServiceInterface) EXPECT() *MockLinkServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockLinkServiceInterface) CreateLink(req *service.CreateLinkRequest) (*service.LinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", req)
	ret0, _ := ret[0].(*service.LinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkServiceInterfaceMockRecorder) CreateLink(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinkServiceInterface)(nil).CreateLink), req)
}

// DeleteLink mocks base method.
func (m *MockLinkServiceInterface) DeleteLink(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkServiceInterfaceMockRecorder) DeleteLink(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkServiceInterface)(nil).DeleteLink), id)
}

// GetByOwnerUserID mocks base method.
func (m *MockLinkServiceInterface) GetByOwnerUserID(ownerUserID string) ([]service.LinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerUserID", ownerUserID)
	ret0, _ := ret[0].([]service.LinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnerUserID indicates an expected call of GetByOwnerUserID.
func (mr *MockLinkServiceInterfaceMockRecorder) GetByOwnerUserID(ownerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerUserID", reflect.TypeOf((*MockLinkServiceInterface)(nil).GetByOwnerUserID), ownerUserID)
}

// GetByOwnerUserIDWithViewer mocks base method.
func (m *MockLinkServiceInterface) GetByOwnerUserIDWithViewer(ownerUserID, viewerName string) ([]service.LinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerUserIDWithViewer", ownerUserID, viewerName)
	ret0, _ := ret[0].([]service.LinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnerUserIDWithViewer indicates an expected call of GetByOwnerUserIDWithViewer.
func (mr *MockLinkServiceInterfaceMockRecorder) GetByOwnerUserIDWithViewer(ownerUserID, viewerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerUserIDWithViewer", reflect.TypeOf((*MockLinkServiceInterface)(nil).GetByOwnerUserIDWithViewer), ownerUserID, viewerName)
}

// MockDocumentationServiceInterface is a mock of DocumentationServiceInterface interface.
type MockDocumentationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentationServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockDocumentationServiceInterfaceMockRecorder is the mock recorder for MockDocumentationServiceInterface.
type MockDocumentationServiceInterfaceMockRecorder struct {
	mock *MockDocumentationServiceInterface
}

// NewMockDocumentationServiceInterface creates a new mock instance.
func NewMockDocumentationServiceInterface(ctrl *gomock.Controller) *MockDocumentationServiceInterface {
	mock := &MockDocumentationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDocumentationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentationServiceInterface) EXPECT() *MockDocumentationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateDocumentation mocks base method.
func (m *MockDocumentationServiceInterface) CreateDocumentation(req *service.CreateDocumentationRequest) (*service.DocumentationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDocumentation", req)
	ret0, _ := ret[0].(*service.DocumentationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDocumentation indicates an expected call of CreateDocumentation.
func (mr *MockDocumentationServiceInterfaceMockRecorder) CreateDocumentation(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDocumentation", reflect.TypeOf((*MockDocumentationServiceInterface)(nil).CreateDocumentation), req)
}

// DeleteDocumentation mocks base method.
func (m *MockDocumentationServiceInterface) DeleteDocumentation(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocumentation", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocumentation indicates an expected call of DeleteDocumentation.
func (mr *MockDocumentationServiceInterfaceMockRecorder) DeleteDocumentation(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocumentation", reflect.TypeOf((*MockDocumentationServiceInterface)(nil).DeleteDocumentation), id)
}

// GetDocumentationByID mocks base method.
func (m *MockDocumentationServiceInterface) GetDocumentationByID(id uuid.UUID) (*service.DocumentationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentationByID", id)
	ret0, _ := ret[0].(*service.DocumentationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocumentationByID indicates an expected call of GetDocumentationByID.
func (mr *MockDocumentationServiceInterfaceMockRecorder) GetDocumentationByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentationByID", reflect.TypeOf((*MockDocumentationServiceInterface)(nil).GetDocumentationByID), id)
}

// GetDocumentationsByTeamID mocks base method.
func (m *MockDocumentationServiceInterface) GetDocumentationsByTeamID(teamID uuid.UUID) ([]service.DocumentationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentationsByTeamID", teamID)
	ret0, _ := ret[0].([]service.DocumentationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocumentationsByTeamID indicates an expected call of GetDocumentationsByTeamID.
func (mr *MockDocumentationServiceInterfaceMockRecorder) GetDocumentationsByTeamID(teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentationsByTeamID", reflect.TypeOf((*MockDocumentationServiceInterface)(nil).GetDocumentationsByTeamID), teamID)
}

// UpdateDocumentation mocks base method.
func (m *MockDocumentationServiceInterface) UpdateDocumentation(id uuid.UUID, req *service.UpdateDocumentationRequest) (*service.DocumentationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDocumentation", id, req)
	ret0, _ := ret[0].(*service.DocumentationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDocumentation indicates an expected call of UpdateDocumentation.
func (mr *MockDocumentationServiceInterfaceMockRecorder) UpdateDocumentation(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDocumentation", reflect.TypeOf((*MockDocumentationServiceInterface)(nil).UpdateDocumentation), id, req)
}
