// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/organization.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/organization.go -destination=mocks/repository/organization.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository
